# Generated by Django 4.2.23 on 2026-01-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_employee_auth_and_sessions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeauthsettings",
            name="rotation_interval_seconds",
            field=models.PositiveIntegerField(default=60),
        ),
    ]
