# Generated by Django 4.2.24 on 2026-07-18 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_employeeauthsettings_rotation_interval_seconds"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmployeeAuthSettings",
        ),
        migrations.RemoveField(
            model_name="employeesession",
            name="user",
        ),
        migrations.DeleteModel(
            name="EmployeePasswordRotationState",
        ),
        migrations.DeleteModel(
            name="EmployeeSession",
        ),
    ]
