# Generated by Django 4.2.23 on 2026-01-26 07:58

import attendance.methods.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import horilla.models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("leave", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0004_alter_employeeauthsettings_rotation_interval_seconds"),
        ("horilla_audit", "0001_initial"),
        ("employee", "0001_initial"),
        ("attendance", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created At"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "attendance_date",
                    models.DateField(
                        validators=[attendance.methods.utils.attendance_date_validate],
                        verbose_name="Attendance date",
                    ),
                ),
                (
                    "attendance_clock_in_date",
                    models.DateField(null=True, verbose_name="Check-In Date"),
                ),
                (
                    "attendance_clock_in",
                    models.TimeField(
                        help_text="First Check-In Time",
                        null=True,
                        verbose_name="Check-In",
                    ),
                ),
                (
                    "attendance_clock_out_date",
                    models.DateField(null=True, verbose_name="Check-Out Date"),
                ),
                (
                    "attendance_clock_out",
                    models.TimeField(
                        help_text="Last Check-Out Time",
                        null=True,
                        verbose_name="Check-Out",
                    ),
                ),
                (
                    "attendance_worked_hour",
                    models.CharField(
                        default="00:00",
                        max_length=10,
                        null=True,
                        validators=[attendance.methods.utils.validate_time_format],
                        verbose_name="Worked Hours",
                    ),
                ),
                (
                    "minimum_hour",
                    models.CharField(
                        default="00:00",
                        max_length=10,
                        validators=[attendance.methods.utils.validate_time_format],
                        verbose_name="Minimum hour",
                    ),
                ),
                (
                    "attendance_overtime",
                    models.CharField(
                        default="00:00",
                        max_length=10,
                        validators=[attendance.methods.utils.validate_time_format],
                        verbose_name="Overtime",
                    ),
                ),
                (
                    "attendance_overtime_approve",
                    models.BooleanField(default=False, verbose_name="Overtime Approve"),
                ),
                (
                    "attendance_validated",
                    models.BooleanField(
                        default=False, verbose_name="Attendance Validate"
                    ),
                ),
                ("at_work_second", models.IntegerField(blank=True, null=True)),
                (
                    "overtime_second",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Overtime In Second"
                    ),
                ),
                ("approved_overtime_second", models.IntegerField(default=0)),
                (
                    "is_validate_request",
                    models.BooleanField(
                        default=False, verbose_name="Is validate request"
                    ),
                ),
                ("is_bulk_request", models.BooleanField(default=False, editable=False)),
                (
                    "is_validate_request_approved",
                    models.BooleanField(
                        default=False, verbose_name="Is validate request approved"
                    ),
                ),
                (
                    "request_description",
                    models.TextField(null=True, verbose_name="Request Description"),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("create_request", "Create Request"),
                            ("update_request", "Update Request"),
                            ("revalidate_request", "Re-validate Request"),
                        ],
                        default="update_request",
                        max_length=18,
                        null=True,
                    ),
                ),
                ("is_holiday", models.BooleanField(default=False)),
                ("requested_data", models.JSONField(editable=False, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="employee.employee",
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "attendance_day",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="base.employeeshiftday",
                        verbose_name="Attendance day",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance",
                "verbose_name_plural": "Attendances",
                "ordering": [
                    "-attendance_date",
                    "employee_id__employee_first_name",
                    "attendance_clock_in",
                ],
                "permissions": [
                    ("change_validateattendance", "Validate Attendance"),
                    ("change_approveovertime", "Change Approve Overtime"),
                ],
            },
        ),
        migrations.CreateModel(
            name="BatchAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created At"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Title")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_modified_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified By",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WorkRecords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "work_record_type",
                    models.CharField(
                        choices=[
                            ("FDP", "Present"),
                            ("HDP", "Half Day Present"),
                            ("ABS", "Absent"),
                            ("HD", "Holiday/Company Leave"),
                            ("CONF", "Conflict"),
                            ("DFT", "Draft"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "at_work",
                    models.CharField(
                        blank=True,
                        default="00:00",
                        max_length=10,
                        null=True,
                        validators=[attendance.methods.utils.validate_time_format],
                    ),
                ),
                (
                    "min_hour",
                    models.CharField(
                        blank=True,
                        default="00:00",
                        max_length=10,
                        null=True,
                        validators=[attendance.methods.utils.validate_time_format],
                    ),
                ),
                (
                    "at_work_second",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "min_hour_second",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("note", models.TextField(max_length=255)),
                ("message", models.CharField(blank=True, max_length=30, null=True)),
                ("is_attendance_record", models.BooleanField(default=False)),
                ("is_leave_record", models.BooleanField(default=False)),
                ("day_percentage", models.FloatField(default=0)),
                ("last_update", models.DateTimeField(blank=True, null=True)),
                (
                    "attendance_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="attendance.attendance",
                    ),
                ),
                (
                    "employee_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee.employee",
                        verbose_name="Employee",
                    ),
                ),
                (
                    "leave_request_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="leave.leaverequest",
                    ),
                ),
                (
                    "shift_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.employeeshift",
                    ),
                ),
            ],
            options={
                "verbose_name": "Work Record",
                "verbose_name_plural": "Work Records",
            },
        ),
        migrations.CreateModel(
            name="HistoricalAttendance",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name="Created At"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "history_title",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("history_description", models.TextField(null=True)),
                ("history_highlight", models.BooleanField(default=False, null=True)),
                (
                    "attendance_date",
                    models.DateField(
                        validators=[attendance.methods.utils.attendance_date_validate],
                        verbose_name="Attendance date",
                    ),
                ),
                (
                    "attendance_clock_in_date",
                    models.DateField(null=True, verbose_name="Check-In Date"),
                ),
                (
                    "attendance_clock_in",
                    models.TimeField(
                        help_text="First Check-In Time",
                        null=True,
                        verbose_name="Check-In",
                    ),
                ),
                (
                    "attendance_clock_out_date",
                    models.DateField(null=True, verbose_name="Check-Out Date"),
                ),
                (
                    "attendance_clock_out",
                    models.TimeField(
                        help_text="Last Check-Out Time",
                        null=True,
                        verbose_name="Check-Out",
                    ),
                ),
                (
                    "attendance_worked_hour",
                    models.CharField(
                        default="00:00",
                        max_length=10,
                        null=True,
                        validators=[attendance.methods.utils.validate_time_format],
                        verbose_name="Worked Hours",
                    ),
                ),
                (
                    "minimum_hour",
                    models.CharField(
                        default="00:00",
                        max_length=10,
                        validators=[attendance.methods.utils.validate_time_format],
                        verbose_name="Minimum hour",
                    ),
                ),
                (
                    "attendance_overtime",
                    models.CharField(
                        default="00:00",
                        max_length=10,
                        validators=[attendance.methods.utils.validate_time_format],
                        verbose_name="Overtime",
                    ),
                ),
                (
                    "attendance_overtime_approve",
                    models.BooleanField(default=False, verbose_name="Overtime Approve"),
                ),
                (
                    "attendance_validated",
                    models.BooleanField(
                        default=False, verbose_name="Attendance Validate"
                    ),
                ),
                ("at_work_second", models.IntegerField(blank=True, null=True)),
                (
                    "overtime_second",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Overtime In Second"
                    ),
                ),
                ("approved_overtime_second", models.IntegerField(default=0)),
                (
                    "is_validate_request",
                    models.BooleanField(
                        default=False, verbose_name="Is validate request"
                    ),
                ),
                ("is_bulk_request", models.BooleanField(default=False, editable=False)),
                (
                    "is_validate_request_approved",
                    models.BooleanField(
                        default=False, verbose_name="Is validate request approved"
                    ),
                ),
                (
                    "request_description",
                    models.TextField(null=True, verbose_name="Request Description"),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("create_request", "Create Request"),
                            ("update_request", "Update Request"),
                            ("revalidate_request", "Re-validate Request"),
                        ],
                        default="update_request",
                        max_length=18,
                        null=True,
                    ),
                ),
                ("is_holiday", models.BooleanField(default=False)),
                ("requested_data", models.JSONField(editable=False, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="employee.employee",
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "attendance_day",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="base.employeeshiftday",
                        verbose_name="Attendance day",
                    ),
                ),
                (
                    "batch_attendance_id",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="attendance.batchattendance",
                        verbose_name="Batch Attendance",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "employee_id",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="employee.employee",
                        verbose_name="Employee",
                    ),
                ),
                (
                    "history_relation",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="history_set",
                        to="attendance.attendance",
                    ),
                ),
                ("history_tags", models.ManyToManyField(to="horilla_audit.audittag")),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified By",
                    ),
                ),
                (
                    "shift_id",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="base.employeeshift",
                        verbose_name="Shift",
                    ),
                ),
                (
                    "work_type_id",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="base.worktype",
                        verbose_name="Work Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Attendance",
                "verbose_name_plural": "historical Attendances",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="GraceTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created At"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "allowed_time",
                    models.CharField(
                        default="00:00:00",
                        max_length=10,
                        validators=[attendance.methods.utils.validate_hh_mm_ss_format],
                        verbose_name="Allowed Time",
                    ),
                ),
                ("allowed_time_in_secs", models.IntegerField()),
                (
                    "allowed_clock_in",
                    models.BooleanField(
                        default=True,
                        help_text="Allcocate this grace time for Check-In Attendance",
                        verbose_name="Allowed Clock-In",
                    ),
                ),
                (
                    "allowed_clock_out",
                    models.BooleanField(
                        default=False,
                        help_text="Allcocate this grace time for Check-Out Attendance",
                        verbose_name="Allowed Clock-Out",
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                (
                    "company_id",
                    models.ManyToManyField(
                        blank=True, to="base.company", verbose_name="Company"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_modified_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified By",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AttendanceValidationCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created At"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "validation_at_work",
                    models.CharField(
                        max_length=10,
                        validators=[attendance.methods.utils.validate_time_format],
                        verbose_name="Worked Hours Auto Approve Till",
                    ),
                ),
                (
                    "minimum_overtime_to_approve",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        validators=[attendance.methods.utils.validate_time_format],
                    ),
                ),
                (
                    "overtime_cutoff",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        validators=[attendance.methods.utils.validate_time_format],
                    ),
                ),
                (
                    "auto_approve_ot",
                    models.BooleanField(default=False, verbose_name="Auto Approve OT"),
                ),
                (
                    "company_id",
                    models.ManyToManyField(
                        blank=True, to="base.company", verbose_name="Company"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_modified_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified By",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AttendanceRequestFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created At"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("file", models.FileField(upload_to=horilla.models.upload_path)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_modified_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified By",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AttendanceRequestComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created At"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "comment",
                    models.TextField(max_length=255, null=True, verbose_name="Comment"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "employee_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee.employee",
                    ),
                ),
                (
                    "files",
                    models.ManyToManyField(
                        blank=True, to="attendance.attendancerequestfile"
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_modified_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified By",
                    ),
                ),
                (
                    "request_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="attendance.attendance",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AttendanceGeneralSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created At"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("time_runner", models.BooleanField(default=True)),
                (
                    "enable_check_in",
                    models.BooleanField(
                        default=True,
                        help_text="Enabling this feature allows employees to record their attendance using the Check-In/Check-Out button.",
                        verbose_name="Enable Check in/Check out",
                    ),
                ),
                (
                    "company_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_modified_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified By",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AttendanceActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created At"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "attendance_date",
                    models.DateField(
                        null=True,
                        validators=[attendance.methods.utils.attendance_date_validate],
                        verbose_name="Attendance Date",
                    ),
                ),
                ("in_datetime", models.DateTimeField(null=True)),
                ("clock_in_date", models.DateField(null=True, verbose_name="In Date")),
                ("clock_in", models.TimeField(verbose_name="Check In")),
                (
                    "clock_out_date",
                    models.DateField(null=True, verbose_name="Out Date"),
                ),
                ("out_datetime", models.DateTimeField(null=True)),
                ("clock_out", models.TimeField(null=True, verbose_name="Check Out")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "employee_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_attendance_activities",
                        to="employee.employee",
                        verbose_name="Employee",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_modified_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified By",
                    ),
                ),
                (
                    "shift_day",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="base.employeeshiftday",
                        verbose_name="Shift Day",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "-attendance_date",
                    "employee_id__employee_first_name",
                    "clock_in",
                ],
            },
        ),
        migrations.AddField(
            model_name="attendance",
            name="batch_attendance_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="attendance.batchattendance",
                verbose_name="Batch Attendance",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="employee_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employee_attendances",
                to="employee.employee",
                verbose_name="Employee",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_modified_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified By",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="shift_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.employeeshift",
                verbose_name="Shift",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="work_type_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.worktype",
                verbose_name="Work Type",
            ),
        ),
        migrations.CreateModel(
            name="AttendanceOverTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created At"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("month", models.CharField(max_length=10, verbose_name="Month")),
                ("month_sequence", models.PositiveSmallIntegerField(default=0)),
                (
                    "year",
                    models.CharField(
                        default="2026", max_length=10, null=True, verbose_name="Year"
                    ),
                ),
                (
                    "worked_hours",
                    models.CharField(
                        default="00:00",
                        max_length=10,
                        null=True,
                        validators=[attendance.methods.utils.validate_time_format],
                        verbose_name="Worked Hours",
                    ),
                ),
                (
                    "pending_hours",
                    models.CharField(
                        default="00:00",
                        max_length=10,
                        null=True,
                        validators=[attendance.methods.utils.validate_time_format],
                        verbose_name="Pending Hours",
                    ),
                ),
                (
                    "overtime",
                    models.CharField(
                        default="00:00",
                        max_length=20,
                        validators=[attendance.methods.utils.validate_time_format],
                        verbose_name="Overtime Hours",
                    ),
                ),
                (
                    "hour_account_second",
                    models.IntegerField(
                        default=0, null=True, verbose_name="Worked Seconds"
                    ),
                ),
                (
                    "hour_pending_second",
                    models.IntegerField(
                        default=0, null=True, verbose_name="Pending Seconds"
                    ),
                ),
                (
                    "overtime_second",
                    models.IntegerField(
                        default=0, null=True, verbose_name="Overtime Seconds"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "employee_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_overtime",
                        to="employee.employee",
                        verbose_name="Employee",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_modified_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hour Account",
                "verbose_name_plural": "Hour Accounts",
                "ordering": ["-year", "-month_sequence"],
                "unique_together": {("employee_id", "month", "year")},
            },
        ),
        migrations.CreateModel(
            name="AttendanceLateComeEarlyOut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("late_come", "Late Come"),
                            ("early_out", "Early Out"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "attendance_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="late_come_early_out",
                        to="attendance.attendance",
                        verbose_name="Attendance",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "employee_id",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="late_come_early_out",
                        to="employee.employee",
                        verbose_name="Employee",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_modified_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified By",
                    ),
                ),
            ],
            options={
                "ordering": ["-attendance_id__attendance_date"],
                "unique_together": {("attendance_id", "type")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("employee_id", "attendance_date")},
        ),
    ]
