# Generated by Django 4.2.24 on 2026-07-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="clock_in_latitude",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Check-In Latitude"
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="clock_in_longitude",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Check-In Longitude"
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="clock_out_latitude",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Check-Out Latitude"
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="clock_out_longitude",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Check-Out Longitude"
            ),
        ),
        migrations.AddField(
            model_name="historicalattendance",
            name="clock_in_latitude",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Check-In Latitude"
            ),
        ),
        migrations.AddField(
            model_name="historicalattendance",
            name="clock_in_longitude",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Check-In Longitude"
            ),
        ),
        migrations.AddField(
            model_name="historicalattendance",
            name="clock_out_latitude",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Check-Out Latitude"
            ),
        ),
        migrations.AddField(
            model_name="historicalattendance",
            name="clock_out_longitude",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Check-Out Longitude"
            ),
        ),
    ]
